site_name: Fraud Detection Models
theme:
  name: material
  font:
    text: Roboto
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - extra
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - mermaid2
nav:
  - Home: "index.md"
  - Baseline: "baseline.md"
  - Model v1: "model_v1.md"
  - Models (v2 and v3): "model_v2_v3.md"
  - Metrics: "metrics.md"
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
