site_name: Fraud Detection Models
theme:
  name: material
  font:
    text: Roboto
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - extra
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - mermaid2
nav:
  - Home: "index.md"
  - Exploratory Data Analysis: "eda.md"
  - Models:
      - Baseline: "baseline.md"
      - Model v1: "model_v1.md"
      - Models (v2 and v3): "model_v2_v3.md"
      - Model v4: "model_v4.md"
  - Metrics: "metrics.md"
  - API: "api.md"
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
